# Uncomment the next line to define a global platform for your project
#use_frameworks!

platform :ios, '11.0'

workspace 'EaseIMKit.xcworkspace'


target 'EaseIMKit' do
  # Pods for EaseIMKit
  pod 'Hyphenate'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'FLAnimatedImage'
  pod 'EMVoiceConvert'

end
